-- Integra los catálogos del antiguo _incoming-activos en el módulo oficial.
-- El borrado se sustituye por archivado recuperable y los documentos pasan
-- a un directorio administrado por MRTI-Activos. Cada ALTER es idempotente.
USE mrti_activos;

SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_componentes' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_componentes ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_componentes' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_componentes ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_impresoras' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_impresoras ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_impresoras' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_impresoras ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_nvr' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_nvr ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_nvr' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_nvr ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_nvr' AND column_name='clave_cifrado_encrypted'),'SELECT 1','ALTER TABLE sap_nvr ADD COLUMN clave_cifrado_encrypted TEXT NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_nvr' AND column_name='codigo_verificacion_encrypted'),'SELECT 1','ALTER TABLE sap_nvr ADD COLUMN codigo_verificacion_encrypted TEXT NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_passwords' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_passwords ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_passwords' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_passwords ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_starlink' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_starlink ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_starlink' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_starlink ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_fortigate' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_fortigate ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_fortigate' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_fortigate ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_dominios' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_dominios ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_dominios' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_dominios ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_mantenimientos' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_mantenimientos ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_mantenimientos' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_mantenimientos ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_unidades' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_unidades ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_unidades' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_unidades ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_documentos' AND column_name='archived_at'),'SELECT 1','ALTER TABLE sap_documentos ADD COLUMN archived_at DATETIME NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_documentos' AND column_name='archived_by'),'SELECT 1','ALTER TABLE sap_documentos ADD COLUMN archived_by CHAR(36) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ddl = IF(EXISTS(SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name='sap_documentos' AND column_name='local_storage_path'),'SELECT 1','ALTER TABLE sap_documentos ADD COLUMN local_storage_path VARCHAR(500) NULL'); PREPARE stmt FROM @ddl; EXECUTE stmt; DEALLOCATE PREPARE stmt;
